In [1]:
# Criando um array de 0 a 90
import numpy as np
vetor = np.arange(0, 100, 10)
vetor

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
# Revertendo o vetor(1)
vetor[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [5]:
# Revertendo o vetor(2)
vetor[[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [7]:
# Criando um vetor aleatório
vetor_ale = np.random.rand(10)
vetor_ale

array([0.30729534, 0.61822408, 0.52311162, 0.82055207, 0.72721489,
       0.32452992, 0.41396786, 0.60370699, 0.84603436, 0.47928433])

In [9]:
# Ordenando o vetor
np.sort(vetor_ale)
# Tamanho os indices das menores valores
idx = np.argsort(vetor_ale)
idx

array([0, 5, 6, 9, 2, 7, 1, 4, 3, 8], dtype=int64)